### ISSUE TITLE
How do I change the black background to transparent?

### ISSUE THREAD

**Issue by AWDPWD** [Jcw87/c2-smb1#2]
How do I change the black background to transparent?
Because I want to use the page background instead of the game's default black background.
After all, the black background doesn’t look good on white theme pages.
(My website is not public, it is only used for internal testing,
For example, when I play other games, I will turn it off.)
I am not good at English :(

**Comment by Jcw87** [comment]
If you are using the Construct 2 editor, you would simply open the 'Intermission' layout, select the 'BG' layer, and change 'Transparent' from 'No' to 'Yes'.

If you are not using the Construct 2 editor, you will have to edit the data.json file to get the result you want. data.json gets obfuscated by Construct 2, so I don't provide support for editing it directly.
